# Welcome to Jekyll!
#
# this config is from https://github.com/mmistakes/mm-github-pages-starter/
# for use with the gem-ified theme https://github.com/mmistakes/minimal-mistakes
# and has been modified acording to https://mmistakes.github.io/minimal-mistakes/docs/configuration/
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UltimApe's [[digital garden]]
subtitle: A place for bees to dance.
name: "@UltimApe"
email:
description: >- # this means to ignore newlines until the next item
  A [[digital garden]] to contain my notes.
  Under Construction
twitter_username: ultimape
github_username: ultimape
minimal_mistakes_skin: default
search: true
repository: "ultimape/garden"


# logo: "/assets/images/88x88.png"
# masthead_title: "My Custom Title"


# Build settings
markdown: CommonMarkGhPages
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
minimal_mistakes_skin: "default"
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# custom debug mode
debug_jekyll: false

# Outputting
url: "garden.wovensoup.com"
baseurl: "/"
permalink: /:categories/:title # do not put a trailing '/' on here or it breaks [[wikilinks]]
paginate: 5 # amount of posts to show
paginate_path: /page:num/
title_separator: "|"

# Breadcrumbs
breadcrumbs: true

# Localization
locale: "en-US"
timezone: "US/Eastern" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Document Metadata Configuration
date_format: "%F"
words_per_minute: 360 # I tested this on myself with https://www.readinglength.com/wpm/

# Search Settings
search_provider: lunr
search_full_content: true # by default Lunr only does 50 words
lunr:
  search_within_pages: true


# config for benbalter/jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true # do not render title twice
  collections: true

# config for benbalter/jekyll-optional-front-matter
optional_front_matter:
  remove_originals: false # preserve the .md files

include:
  - _pages
  - _weeds


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - LICENCE
  - CNAME


# Plugins (previously gems:)
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings # if no title is set, use the first instance of h1/h2/h3
  - jekyll-default-layout
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-readme-index # makes the readme.md file turn into the index.html
  - jekyll-commonmark-ghpages
 # - jekyll-archives  # this doesn't work with GitHub Pages

author:
  name   : "UltimApe"
  avatar : "/assets/images/bio-photo.jpg"
  bio    :  >- # this means to ignore newlines until the next item
   "I'm a cyborg slime-mold brain fungus piloting a complex exosuit made of flesh.
   Wandering scholar, and informavore."
  location : "The Spider's Web."
  links:
    - label: "WovenSoup"
      icon: "fas fa-fw fa-link"
      url: "https://wovensoup.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ultimape"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ultimape/garden"
    # - label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

# Opengraph Meta Data
twitter:
  username: "ultimape"

# og_image: /assets/images/site-logo.png 

social:
  type: "Person"
  name: "UltimApe"
  links:
    - "https://wovensoup.com"
    - "https://twitter.com/ultimape"
    - "https://mastodon.social/ultimape"
    - "https://are.na/ultiampe/"
    - "https://github.com/ultimape/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ultimape"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ultimape/garden/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

#collections:
#  weeds:
#     output: true 
#     permalink: :slug/

defaults:
  - scope:
      path: ""
    values:
      read_time: true
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      show_date: true
      paginate: false
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      # show_date: true # this doesn't work on pages
      read_time: true

  # _weeds
  - scope:
      path: "weeds"
    values:
      layout: weed
      author_profile: true
      read_time: true

  # tag pages from jekyll-archives
  # - scope:
  #     path: ""
  #     type: tag
  #   values:
  #     author_profile: true

  # category pages from  from jekyll-archives
  # - scope:
  #     path: ""
  #     type: category
  #   values:
  #     comments: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# use this if jekyll-archives is installted
# category_archive:
#   type: jekyll-archives
#   path: /categories/
# tag_archive:
#   type: jekyll-archives
#   path: /tags/
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/
